UPDATE [AnimalWelfare] SET [SummaryImpactOnAnimalWelfare] = NULL WHERE DATALENGTH([SummaryImpactOnAnimalWelfare]) = 0
UPDATE [AnimalWelfareSpecies] SET [WelfareIssueIndicatorComments] = NULL WHERE DATALENGTH([WelfareIssueIndicatorComments]) = 0
UPDATE [AnimalWelfareSpecies] SET [FreedomFromHungerAndThirstComments] = NULL WHERE DATALENGTH([FreedomFromHungerAndThirstComments]) = 0
UPDATE [AnimalWelfareSpecies] SET [FreedomFromDiscomfortComments] = NULL WHERE DATALENGTH([FreedomFromDiscomfortComments]) = 0
UPDATE [AnimalWelfareSpecies] SET [FreedomFromPainOrInjuryComments] = NULL WHERE DATALENGTH([FreedomFromPainOrInjuryComments]) = 0
UPDATE [AnimalWelfareSpecies] SET [FreedomToExpressNormalBehaviourComments] = NULL WHERE DATALENGTH([FreedomToExpressNormalBehaviourComments]) = 0
UPDATE [AnimalWelfareSpecies] SET [FreedomFromFearAndDistressComments] = NULL WHERE DATALENGTH([FreedomFromFearAndDistressComments]) = 0
UPDATE [AnimalWelfareSpecies] SET [PotentialToReduceWelfareImplicationsComments] = NULL WHERE DATALENGTH([PotentialToReduceWelfareImplicationsComments]) = 0
UPDATE [AnimalWelfareSpecies] SET [ProportionOfAnimalsAffectedSufferingSeverelyComments] = NULL WHERE DATALENGTH([ProportionOfAnimalsAffectedSufferingSeverelyComments]) = 0
UPDATE [ApproachToControl] SET [ControlsAboveTheHoldingLevelComments] = NULL WHERE DATALENGTH([ControlsAboveTheHoldingLevelComments]) = 0
UPDATE [ApproachToControlSpecies] SET [CurrentControlMechanismsComments] = NULL WHERE DATALENGTH([CurrentControlMechanismsComments]) = 0
UPDATE [ApproachToControlSpecies] SET [OtherControlMechanismsComments] = NULL WHERE DATALENGTH([OtherControlMechanismsComments]) = 0
UPDATE [ApproachToControlSpecies] SET [UptakeAtHoldingLevelComments] = NULL WHERE DATALENGTH([UptakeAtHoldingLevelComments]) = 0
UPDATE [ApproachToControlSpecies] SET [WelfareEffectComments] = NULL WHERE DATALENGTH([WelfareEffectComments]) = 0
UPDATE [ApproachToControlSpecies] SET [PotentialToReduceRiskComments] = NULL WHERE DATALENGTH([PotentialToReduceRiskComments]) = 0
UPDATE [ApproachToControlSpecies] SET [PotentialToReduceHumanExposureComments] = NULL WHERE DATALENGTH([PotentialToReduceHumanExposureComments]) = 0
UPDATE [ApproachToControlSpecies] SET [VaccinesAvailableIndicatorComments] = NULL WHERE DATALENGTH([VaccinesAvailableIndicatorComments]) = 0
UPDATE [ApproachToControlSpecies] SET [ControlsAtTheHoldingLevelComments] = NULL WHERE DATALENGTH([ControlsAtTheHoldingLevelComments]) = 0
UPDATE [ApproachToControlSpecies] SET [Compensation] = NULL WHERE DATALENGTH([Compensation]) = 0
UPDATE [ApproachToControlSpecies] SET [LevelOfNationalPreparednessComments] = NULL WHERE DATALENGTH([LevelOfNationalPreparednessComments]) = 0
UPDATE [AreasOfUncertainty] SET [AreasOfUncertaintySummary] = NULL WHERE DATALENGTH([AreasOfUncertaintySummary]) = 0
UPDATE [CurrentSurveillanceActivitiesSpecies] SET [PurposeAndDetail] = NULL WHERE DATALENGTH([PurposeAndDetail]) = 0
UPDATE [Epidemiology] SET [SuspectCaseDefinition] = NULL WHERE DATALENGTH([SuspectCaseDefinition]) = 0
UPDATE [Epidemiology] SET [ProbableCaseDefinition] = NULL WHERE DATALENGTH([ProbableCaseDefinition]) = 0
UPDATE [Epidemiology] SET [ConfirmedCaseDefinition] = NULL WHERE DATALENGTH([ConfirmedCaseDefinition]) = 0
UPDATE [Epidemiology] SET [DiagnosisMechanismComments] = NULL WHERE DATALENGTH([DiagnosisMechanismComments]) = 0
UPDATE [Epidemiology] SET [AgentDescription] = NULL WHERE DATALENGTH([AgentDescription]) = 0
UPDATE [Epidemiology] SET [TherapeuticAgentSusceptibility] = NULL WHERE DATALENGTH([TherapeuticAgentSusceptibility]) = 0
UPDATE [Epidemiology] SET [PersistenceInEnvironmentIndicatorComments] = NULL WHERE DATALENGTH([PersistenceInEnvironmentIndicatorComments]) = 0
UPDATE [Epidemiology] SET [SpreadMechanismComments] = NULL WHERE DATALENGTH([SpreadMechanismComments]) = 0
UPDATE [EpidemiologySpecies] SET [DifferentialDiagnoses] = NULL WHERE DATALENGTH([DifferentialDiagnoses]) = 0
UPDATE [EpidemiologySpecies] SET [PotentialForSilentSpreadComments] = NULL WHERE DATALENGTH([PotentialForSilentSpreadComments]) = 0
UPDATE [EpidemiologySpecies] SET [ClinicalSigns] = NULL WHERE DATALENGTH([ClinicalSigns]) = 0
UPDATE [EpidemiologySpecies] SET [PathologicalFeatures] = NULL WHERE DATALENGTH([PathologicalFeatures]) = 0
UPDATE [EpidemiologySpecies] SET [MortalityIndicatorComments] = NULL WHERE DATALENGTH([MortalityIndicatorComments]) = 0
UPDATE [EpidemiologySpecies] SET [DurationOfDiseaseComments] = NULL WHERE DATALENGTH([DurationOfDiseaseComments]) = 0
UPDATE [EpidemiologySpecies] SET [DetectionMethodTypeComments] = NULL WHERE DATALENGTH([DetectionMethodTypeComments]) = 0
UPDATE [EpidemiologySpecies] SET [TransmissionMechanismComments] = NULL WHERE DATALENGTH([TransmissionMechanismComments]) = 0
UPDATE [EpidemiologySpecies] SET [RateOfSpreadOnPremisesComments] = NULL WHERE DATALENGTH([RateOfSpreadOnPremisesComments]) = 0
UPDATE [EpidemiologySpecies] SET [WildlifeReservoirIndicatorComments] = NULL WHERE DATALENGTH([WildlifeReservoirIndicatorComments]) = 0
UPDATE [EpidemiologySpecies] SET [IncreaseUnderstandingPotentialComments] = NULL WHERE DATALENGTH([IncreaseUnderstandingPotentialComments]) = 0
--UPDATE [ErrorLog] SET [StackTrace] = NULL WHERE DATALENGTH([StackTrace]) = 0
UPDATE [GeographicDistribution] SET [GBPresenceIndicatorComments] = NULL WHERE DATALENGTH([GBPresenceIndicatorComments]) = 0
UPDATE [GeographicDistribution] SET [CurrentPrevalenceInGBComments] = NULL WHERE DATALENGTH([CurrentPrevalenceInGBComments]) = 0
UPDATE [GeographicDistribution] SET [DateOfMostRecentOccurrenceInGBComments] = NULL WHERE DATALENGTH([DateOfMostRecentOccurrenceInGBComments]) = 0
UPDATE [GeographicDistribution] SET [RiskOfIntroductionToGBComments] = NULL WHERE DATALENGTH([RiskOfIntroductionToGBComments]) = 0
UPDATE [GeographicDistribution] SET [GlobalGeographicDistributionComments] = NULL WHERE DATALENGTH([GlobalGeographicDistributionComments]) = 0
UPDATE [GeographicDistributionSpecies] SET [NumberOfCasesPerYearInGBComments] = NULL WHERE DATALENGTH([NumberOfCasesPerYearInGBComments]) = 0
UPDATE [GeographicDistributionSpecies] SET [PotentialForRiskChangeComments] = NULL WHERE DATALENGTH([PotentialForRiskChangeComments]) = 0
UPDATE [HumanHealth] SET [ZoonoticIndicatorComments] = NULL WHERE DATALENGTH([ZoonoticIndicatorComments]) = 0
UPDATE [HumanHealth] SET [HumanTransmissionMechanismComments] = NULL WHERE DATALENGTH([HumanTransmissionMechanismComments]) = 0
UPDATE [HumanHealth] SET [SymptomsOfHumanDisease] = NULL WHERE DATALENGTH([SymptomsOfHumanDisease]) = 0
UPDATE [HumanHealth] SET [TransmissibilityIndicatorComments] = NULL WHERE DATALENGTH([TransmissibilityIndicatorComments]) = 0
UPDATE [HumanHealth] SET [ModalSeverityOfHumanDiseaseComments] = NULL WHERE DATALENGTH([ModalSeverityOfHumanDiseaseComments]) = 0
UPDATE [HumanHealth] SET [MaximumSeverityOfHumanDiseaseComments] = NULL WHERE DATALENGTH([MaximumSeverityOfHumanDiseaseComments]) = 0
UPDATE [HumanHealth] SET [GeographicDistributionOfHumanDiseaseComments] = NULL WHERE DATALENGTH([GeographicDistributionOfHumanDiseaseComments]) = 0
UPDATE [HumanHealth] SET [AnnualNumberOfHumanCasesInGBComments] = NULL WHERE DATALENGTH([AnnualNumberOfHumanCasesInGBComments]) = 0
UPDATE [HumanHealth] SET [AverageCostPerCaseComments] = NULL WHERE DATALENGTH([AverageCostPerCaseComments]) = 0
UPDATE [HumanHealth] SET [IndirectEconomicCostOfHumanIllnessComments] = NULL WHERE DATALENGTH([IndirectEconomicCostOfHumanIllnessComments]) = 0
UPDATE [HumanHealth] SET [UncertaintyComments] = NULL WHERE DATALENGTH([UncertaintyComments]) = 0
UPDATE [HumanHealth] SET [ImpactOnHumanHealth] = NULL WHERE DATALENGTH([ImpactOnHumanHealth]) = 0
UPDATE [HumanHealthSpecies] SET [LevelOfHumanExposureToAnimalOrProductsComments] = NULL WHERE DATALENGTH([LevelOfHumanExposureToAnimalOrProductsComments]) = 0
UPDATE [HumanHealthSpecies] SET [AttributableFractionComments] = NULL WHERE DATALENGTH([AttributableFractionComments]) = 0
UPDATE [InternationalTrade] SET [StatutoryObligationToControlComments] = NULL WHERE DATALENGTH([StatutoryObligationToControlComments]) = 0
UPDATE [InternationalTrade] SET [ReestablishmentOfTradingStatusComments] = NULL WHERE DATALENGTH([ReestablishmentOfTradingStatusComments]) = 0
UPDATE [InternationalTrade] SET [PotentialForRegionalisationComments] = NULL WHERE DATALENGTH([PotentialForRegionalisationComments]) = 0
UPDATE [InternationalTrade] SET [RangeOfCommoditiesCompromisedComments] = NULL WHERE DATALENGTH([RangeOfCommoditiesCompromisedComments]) = 0
UPDATE [InternationalTrade] SET [ImpactOnInternationalTrade] = NULL WHERE DATALENGTH([ImpactOnInternationalTrade]) = 0
UPDATE [InternationalTradeSpecies] SET [CommercialTradeComments] = NULL WHERE DATALENGTH([CommercialTradeComments]) = 0
UPDATE [InternationalTradeSpecies] SET [ImpactOnLevelOfImportsComments] = NULL WHERE DATALENGTH([ImpactOnLevelOfImportsComments]) = 0
UPDATE [InternationalTradeSpecies] SET [ImportanceOfExportTradeComments] = NULL WHERE DATALENGTH([ImportanceOfExportTradeComments]) = 0
UPDATE [InternationalTradeSpecies] SET [ImpactOnIntraCommunityFlowsComments] = NULL WHERE DATALENGTH([ImpactOnIntraCommunityFlowsComments]) = 0
UPDATE [InternationalTradeSpecies] SET [ImpactOnThirdCountryFlowsComments] = NULL WHERE DATALENGTH([ImpactOnThirdCountryFlowsComments]) = 0
UPDATE [InternationalTradeSpecies] SET [ExportMarketValueComments] = NULL WHERE DATALENGTH([ExportMarketValueComments]) = 0
UPDATE [LegislationAndMandates] SET [ApplicableLegislationAndMandatesComments] = NULL WHERE DATALENGTH([ApplicableLegislationAndMandatesComments]) = 0
UPDATE [LegislationAndMandates] SET [LegislationOverview] = NULL WHERE DATALENGTH([LegislationOverview]) = 0
--UPDATE [LegislativeReference] SET [NoteText] = NULL WHERE DATALENGTH([NoteText]) = 0
UPDATE [OpportunityToAddValue] SET [OpportunityToAddValueSummary] = NULL WHERE DATALENGTH([OpportunityToAddValueSummary]) = 0
--UPDATE [ProfileQuestion] SET [UserGuidance] = NULL WHERE DATALENGTH([UserGuidance]) = 0
UPDATE [PublicAndStakeholderPerception] SET [PublicAndStakeholderPerceptionSummary] = NULL WHERE DATALENGTH([PublicAndStakeholderPerceptionSummary]) = 0
--UPDATE [ReviewComment] SET [Comment] = NULL WHERE DATALENGTH([Comment]) = 0
UPDATE [RiskSpecies] SET [RiskScenarios] = NULL WHERE DATALENGTH([RiskScenarios]) = 0
--UPDATE [ScientificPaperReference] SET [NoteText] = NULL WHERE DATALENGTH([NoteText]) = 0
--UPDATE [SourceOfFurtherInformation] SET [NoteText] = NULL WHERE DATALENGTH([NoteText]) = 0
UPDATE [Species] SET [CommercialTradeComments] = NULL WHERE DATALENGTH([CommercialTradeComments]) = 0
UPDATE [Species] SET [ImportanceOfExportTradeComments] = NULL WHERE DATALENGTH([ImportanceOfExportTradeComments]) = 0
UPDATE [Species] SET [ImpactOnLevelOfImportsComments] = NULL WHERE DATALENGTH([ImpactOnLevelOfImportsComments]) = 0
UPDATE [Species] SET [ImpactOnIntraCommunityFlowsComments] = NULL WHERE DATALENGTH([ImpactOnIntraCommunityFlowsComments]) = 0
UPDATE [Species] SET [ImpactOnThirdCountryFlowsComments] = NULL WHERE DATALENGTH([ImpactOnThirdCountryFlowsComments]) = 0
UPDATE [Species] SET [ExportMarketValueComments] = NULL WHERE DATALENGTH([ExportMarketValueComments]) = 0
UPDATE [Summary] SET [Description] = NULL WHERE DATALENGTH([Description]) = 0
UPDATE [Summary] SET [AffectedSpeciesComments] = NULL WHERE DATALENGTH([AffectedSpeciesComments]) = 0
UPDATE [Summary] SET [RevisionHistory] = NULL WHERE DATALENGTH([RevisionHistory]) = 0
UPDATE [Surveillance] SET [SummaryOfSurveillanceActivities] = NULL WHERE DATALENGTH([SummaryOfSurveillanceActivities]) = 0
UPDATE [WiderSociety] SET [PotentialUnplannedCostToExchequerComments] = NULL WHERE DATALENGTH([PotentialUnplannedCostToExchequerComments]) = 0
UPDATE [WiderSociety] SET [GlobalEnvironmentComments] = NULL WHERE DATALENGTH([GlobalEnvironmentComments]) = 0
UPDATE [WiderSociety] SET [LocalEnvironmentComments] = NULL WHERE DATALENGTH([LocalEnvironmentComments]) = 0
UPDATE [WiderSociety] SET [WiderRuralCommunityComments] = NULL WHERE DATALENGTH([WiderRuralCommunityComments]) = 0
UPDATE [WiderSociety] SET [TotalSurveillanceCostsComments] = NULL WHERE DATALENGTH([TotalSurveillanceCostsComments]) = 0
UPDATE [WiderSociety] SET [ImpactOnSocietySummary] = NULL WHERE DATALENGTH([ImpactOnSocietySummary]) = 0
UPDATE [WiderSociety] SET [FFGCostsSummary] = NULL WHERE DATALENGTH([FFGCostsSummary]) = 0
UPDATE [WiderSocietySpecies] SET [LocalAgriculturalEconomyComments] = NULL WHERE DATALENGTH([LocalAgriculturalEconomyComments]) = 0
