<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>
  <xsl:template match="root">

    IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sppPrioritisationCalculation]') AND type in (N'P', N'PC'))
    DROP PROCEDURE [dbo].[sppPrioritisationCalculation]
    GO

    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
    -- =============================================
    --  This stored procedure was autogenerated by the Profiles
    --  CodeGen application on <xsl:value-of select="@datetime"/> .
	  -- =============================================
	  CREATE PROCEDURE sppPrioritisationCalculation
	  @ProfileVersionId uniqueidentifier
	  AS
	  BEGIN
	  -- SET NOCOUNT ON added to prevent extra result sets from
	  -- interfering with SELECT statements.
	  SET NOCOUNT ON;

	  DECLARE @SpeciesId uniqueidentifier

	  DELETE
	  [ProfileVersionSpeciesPrioritisation]
	  WHERE
	  [ProfileVersionId] = @ProfileVersionId

	  DELETE
	  [ProfileVersionPrioritisedSpecies]
	  WHERE
	  [ProfileVersionId] = @ProfileVersionId
	  
	  DECLARE @SpeciesList TABLE
	  (
	  SpeciesId uniqueidentifier
	  )

	  DECLARE csrProfileSpecies CURSOR FOR
	  SELECT
	  [SpeciesId]
	  FROM
	  [ProfileVersionSpecies] INNER JOIN [luAffectedSpeciesType] ON [ProfileVersionSpecies].[AffectedSpeciesTypeId] = [luAffectedSpeciesType].[Id]
	  WHERE
	  [ProfileVersionId] = @ProfileVersionId AND
	  [luAffectedSpeciesType].[Name] = 'Profiled'
	  FOR READ ONLY

	  OPEN csrProfileSpecies

	  FETCH NEXT FROM csrProfileSpecies INTO @SpeciesId

	  WHILE @@FETCH_STATUS = 0 BEGIN

	  INSERT INTO @SpeciesList
	  SELECT
	  [Id]
	  FROM
	  dbo.GetChildSpecies(@SpeciesId)

	  INSERT INTO [ProfileVersionPrioritisedSpecies]
	  SELECT
	  @ProfileVersionId,
	  SpeciesId,
	  @SpeciesId
	  FROM
	  @SpeciesList
	  
	  DECLARE @PrioritisationCriterionValueId uniqueidentifier
	  DECLARE @IsMissing bit

	  <xsl:for-each select="Category">
      -- <xsl:value-of select="@Name"/>
      <xsl:variable name="CategoryName" select="@Name"/>
	  <xsl:variable name="HasIrrelevanceTest" select="count(Irrelevance/@IrrelevanceFieldId) > 0"/>
		  
	  <xsl:if test="$HasIrrelevanceTest">
		  <xsl:for-each select="Irrelevance">

			  <xsl:variable name="IrrelevanceNumber" select="position()"/>
			  <xsl:variable name="IrrelevanceFieldId" select="@IrrelevanceFieldId"/>

			  DECLARE @<xsl:value-of select="$CategoryName"/>IrrelevanceFlag<xsl:value-of select="$IrrelevanceNumber"/> <xsl:choose><xsl:when test="@IrrelevanceValueId"> uniqueidentifier</xsl:when><xsl:otherwise> bit</xsl:otherwise></xsl:choose>

			  <xsl:for-each select="../../ProfileField[@Id = $IrrelevanceFieldId]">
				  <xsl:choose>
					  <xsl:when test="./@IsPerSpecies = 0">
						  SELECT
						  @<xsl:value-of select="$CategoryName"/>IrrelevanceFlag<xsl:value-of select="$IrrelevanceNumber"/> = [<xsl:value-of select="./@FieldName"/>]
						  FROM
						  [<xsl:value-of select="./@SectionName"/>]
						  WHERE
						  [ProfileVersionId] = @ProfileVersionId
					  </xsl:when>
					  <xsl:otherwise>
						  SELECT
						  @<xsl:value-of select="$CategoryName"/>IrrelevanceFlag<xsl:value-of select="$IrrelevanceNumber"/> = [<xsl:value-of select="./@FieldName"/>]
						  FROM
						  [<xsl:value-of select="./@SectionName"/>Species]
						  WHERE
						  [ProfileVersionId] = @ProfileVersionId AND
						  [SpeciesId] = @SpeciesId
					  </xsl:otherwise>
				  </xsl:choose>
			  </xsl:for-each>
			  
		  </xsl:for-each>
		 
	  </xsl:if>
		  
	<xsl:variable name="IrrelevanceTest">
		<xsl:for-each select="Irrelevance">
			<xsl:if test="position()>1">OR </xsl:if>
			<xsl:choose>
				<xsl:when test="@IrrelevanceValueId">
					@<xsl:value-of select="../@Name"/>IrrelevanceFlag<xsl:value-of select="position()"/> = '<xsl:value-of select="@IrrelevanceValueId"/>'
				</xsl:when>
				<xsl:otherwise>
					@<xsl:value-of select="../@Name"/>IrrelevanceFlag<xsl:value-of select="position()"/> = <xsl:value-of select="@IrrelevanceFlag"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:for-each>
	</xsl:variable>

	<xsl:variable name="MissingTest">
		@PrioritisationCriterionValueId IS NOT NULL
		<xsl:for-each select="Irrelevance">
			AND @<xsl:value-of select="../@Name"/>IrrelevanceFlag<xsl:value-of select="position()"/> IS NOT NULL
		</xsl:for-each>
	</xsl:variable>
		  
      <xsl:for-each select="Criterion">
        --<xsl:value-of select="@Name"/>
        <xsl:variable name="CriterionId" select="@Id"/>
        <xsl:variable name="CriterionName" select="@Code"/>
        <xsl:variable name="MappingFlag" select="@MappingFlag"/>
        <xsl:variable name="TrueMapping" select="@TrueMapping"/>
        <xsl:variable name="FalseMapping" select="@FalseMapping"/>
        
        <xsl:if test="$MappingFlag">
        DECLARE @<xsl:value-of select="$CriterionName"/>MappingFlag bit
        
          <xsl:for-each select="../../ProfileField[@Id = $MappingFlag]">
            <xsl:choose>
              <xsl:when test="./@IsPerSpecies = 0">
                SELECT
                @<xsl:value-of select="$CriterionName"/>MappingFlag = [<xsl:value-of select="./@FieldName"/>]
                FROM
                [<xsl:value-of select="./@SectionName"/>]
                WHERE
                [ProfileVersionId] = @ProfileVersionId
              </xsl:when>
              <xsl:otherwise>
                SELECT
                @<xsl:value-of select="$CriterionName"/>MappingFlag = [<xsl:value-of select="./@FieldName"/>]
                FROM
                [<xsl:value-of select="./@SectionName"/>Species] 
                WHERE
                [ProfileVersionId] = @ProfileVersionId AND
                [SpeciesId] = @SpeciesId
              </xsl:otherwise>
            </xsl:choose>
          </xsl:for-each>

          IF @<xsl:value-of select="$CriterionName"/>MappingFlag = 1 BEGIN
        </xsl:if>
        
        <xsl:for-each select="../../ProfileField[@Id = $TrueMapping]">
          <xsl:choose>
            <xsl:when test="./@IsPerSpecies = 0">
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [<xsl:value-of select="./@SectionName"/>] INNER JOIN [<xsl:value-of select="./@ReferenceTableName"/>] ON [<xsl:value-of select="./@SectionName"/>].[<xsl:value-of select="./@FieldName"/>] = [<xsl:value-of select="./@ReferenceTableName"/>].[Id]
              <xsl:choose>
                <xsl:when test="$MappingFlag">
                  INNER JOIN [PrioritisationCriterionValue] ON [<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue] = LEFT([PrioritisationCriterionValue].[CriterionValue], LEN([<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue]))
                </xsl:when>
                <xsl:otherwise>
                  INNER JOIN [PrioritisationCriterionValue] ON [<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                </xsl:otherwise>
              </xsl:choose>
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '<xsl:value-of select="$CriterionId"/>'
            </xsl:when>
            <xsl:otherwise>
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [<xsl:value-of select="./@SectionName"/>Species] INNER JOIN [<xsl:value-of select="./@ReferenceTableName"/>] ON [<xsl:value-of select="./@SectionName"/>Species].[<xsl:value-of select="./@FieldName"/>] = [<xsl:value-of select="./@ReferenceTableName"/>].[Id]
              <xsl:choose>
              <xsl:when test="$MappingFlag">
                INNER JOIN [PrioritisationCriterionValue] ON [<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue] = LEFT([PrioritisationCriterionValue].[CriterionValue], LEN([<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue]))
              </xsl:when>
                <xsl:otherwise>
                  INNER JOIN [PrioritisationCriterionValue] ON [<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                </xsl:otherwise>
            </xsl:choose>
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '<xsl:value-of select="$CriterionId"/>'
            </xsl:otherwise>
          </xsl:choose>
        </xsl:for-each>

        <xsl:if test="$MappingFlag">
			END

			IF @<xsl:value-of select="$CriterionName"/>MappingFlag = 0 BEGIN

		<xsl:for-each select="../../ProfileField[@Id = $FalseMapping]">
          <xsl:choose>
            <xsl:when test="./@IsPerSpecies = 0">
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [<xsl:value-of select="./@SectionName"/>] INNER JOIN [<xsl:value-of select="./@ReferenceTableName"/>] ON [<xsl:value-of select="./@SectionName"/>].[<xsl:value-of select="./@FieldName"/>] = [<xsl:value-of select="./@ReferenceTableName"/>].[Id]
              INNER JOIN [PrioritisationCriterionValue] ON [<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue] = RIGHT([PrioritisationCriterionValue].[CriterionValue], LEN([<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue]))
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '<xsl:value-of select="$CriterionId"/>'
            </xsl:when>
            <xsl:otherwise>
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [<xsl:value-of select="./@SectionName"/>Species] INNER JOIN [<xsl:value-of select="./@ReferenceTableName"/>] ON [<xsl:value-of select="./@SectionName"/>Species].[<xsl:value-of select="./@FieldName"/>] = [<xsl:value-of select="./@ReferenceTableName"/>].[Id]
              INNER JOIN [PrioritisationCriterionValue] ON [<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue] = RIGHT([PrioritisationCriterionValue].[CriterionValue], LEN([<xsl:value-of select="./@ReferenceTableName"/>].[LookupValue]))
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '<xsl:value-of select="$CriterionId"/>'
            </xsl:otherwise>
          </xsl:choose>
        </xsl:for-each>
          
          END
          
        </xsl:if>

		  IF <xsl:value-of select="$MissingTest"/> BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  <xsl:if test="$HasIrrelevanceTest">
			  IF <xsl:value-of select="$IrrelevanceTest"/> BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		</xsl:if>

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '<xsl:value-of select="$CriterionId"/>',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  </xsl:for-each>
      
      </xsl:for-each>

    DELETE FROM @SpeciesList
    
    FETCH NEXT FROM csrProfileSpecies INTO @SpeciesId

    END

    CLOSE csrProfileSpecies
    DEALLOCATE csrProfileSpecies

    END
    GO

    GRANT EXECUTE ON [dbo].[sppPrioritisationCalculation] TO [VLAProfilesUser]
    GO
    
  </xsl:template>
  
</xsl:stylesheet>
