'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SsoUserManagement
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VlaUser", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class VlaUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As System.Guid
        
        Private TokenIdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LoginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrganisationNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneNumberField As String
        
        Private PasscodeIndex1Field As Integer
        
        Private PasscodeIndex2Field As Integer
        
        Private IsAllocatedOnePointFiveSystemsField As Boolean
        
        Private IsLoginFixedField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SystemsField() As SsoUserManagement.VlaSystem
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Friend Property Id() As System.Guid
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Friend Property TokenId() As System.Guid
            Get
                Return Me.TokenIdField
            End Get
            Set
                If (Me.TokenIdField.Equals(value) <> true) Then
                    Me.TokenIdField = value
                    Me.RaisePropertyChanged("TokenId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Friend Property Login() As String
            Get
                Return Me.LoginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LoginField, value) <> true) Then
                    Me.LoginField = value
                    Me.RaisePropertyChanged("Login")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Friend Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Friend Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Friend Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Friend Property OrganisationName() As String
            Get
                Return Me.OrganisationNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrganisationNameField, value) <> true) Then
                    Me.OrganisationNameField = value
                    Me.RaisePropertyChanged("OrganisationName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Friend Property PhoneNumber() As String
            Get
                Return Me.PhoneNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneNumberField, value) <> true) Then
                    Me.PhoneNumberField = value
                    Me.RaisePropertyChanged("PhoneNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Friend Property PasscodeIndex1() As Integer
            Get
                Return Me.PasscodeIndex1Field
            End Get
            Set
                If (Me.PasscodeIndex1Field.Equals(value) <> true) Then
                    Me.PasscodeIndex1Field = value
                    Me.RaisePropertyChanged("PasscodeIndex1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Friend Property PasscodeIndex2() As Integer
            Get
                Return Me.PasscodeIndex2Field
            End Get
            Set
                If (Me.PasscodeIndex2Field.Equals(value) <> true) Then
                    Me.PasscodeIndex2Field = value
                    Me.RaisePropertyChanged("PasscodeIndex2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=10)>  _
        Friend Property IsAllocatedOnePointFiveSystems() As Boolean
            Get
                Return Me.IsAllocatedOnePointFiveSystemsField
            End Get
            Set
                If (Me.IsAllocatedOnePointFiveSystemsField.Equals(value) <> true) Then
                    Me.IsAllocatedOnePointFiveSystemsField = value
                    Me.RaisePropertyChanged("IsAllocatedOnePointFiveSystems")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=11)>  _
        Friend Property IsLoginFixed() As Boolean
            Get
                Return Me.IsLoginFixedField
            End Get
            Set
                If (Me.IsLoginFixedField.Equals(value) <> true) Then
                    Me.IsLoginFixedField = value
                    Me.RaisePropertyChanged("IsLoginFixed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Friend Property Systems() As SsoUserManagement.VlaSystem()
            Get
                Return Me.SystemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SystemsField, value) <> true) Then
                    Me.SystemsField = value
                    Me.RaisePropertyChanged("Systems")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VlaSystem", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class VlaSystem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UrlField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RolesField() As SsoUserManagement.VlaRole
        
        Private RequiresOnePointFiveField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Friend Property Id() As System.Guid
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Friend Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Friend Property Url() As String
            Get
                Return Me.UrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UrlField, value) <> true) Then
                    Me.UrlField = value
                    Me.RaisePropertyChanged("Url")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Friend Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Friend Property Roles() As SsoUserManagement.VlaRole()
            Get
                Return Me.RolesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RolesField, value) <> true) Then
                    Me.RolesField = value
                    Me.RaisePropertyChanged("Roles")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Friend Property RequiresOnePointFive() As Boolean
            Get
                Return Me.RequiresOnePointFiveField
            End Get
            Set
                If (Me.RequiresOnePointFiveField.Equals(value) <> true) Then
                    Me.RequiresOnePointFiveField = value
                    Me.RaisePropertyChanged("RequiresOnePointFive")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VlaRole", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class VlaRole
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Friend Property Id() As System.Guid
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Friend Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="VlaPartialUser", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Friend Class VlaPartialUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LoginField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        Private IsLockedOutField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Friend Property Id() As System.Guid
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Friend Property Login() As String
            Get
                Return Me.LoginField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LoginField, value) <> true) Then
                    Me.LoginField = value
                    Me.RaisePropertyChanged("Login")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Friend Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Friend Property IsLockedOut() As Boolean
            Get
                Return Me.IsLockedOutField
            End Get
            Set
                If (Me.IsLockedOutField.Equals(value) <> true) Then
                    Me.IsLockedOutField = value
                    Me.RaisePropertyChanged("IsLockedOut")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SsoUserManagement.ServiceSoap")>  _
    Friend Interface ServiceSoap
        
        'CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUser", ReplyAction:="*")>  _
        Function GetUser(ByVal request As SsoUserManagement.GetUserRequest) As SsoUserManagement.GetUserResponse
        
        'CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FindUsersByEmail", ReplyAction:="*")>  _
        Function FindUsersByEmail(ByVal request As SsoUserManagement.FindUsersByEmailRequest) As SsoUserManagement.FindUsersByEmailResponse
        
        'CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FindUserByLogin", ReplyAction:="*")>  _
        Function FindUserByLogin(ByVal request As SsoUserManagement.FindUserByLoginRequest) As SsoUserManagement.FindUserByLoginResponse
        
        'CODEGEN: Generating message contract since element name FindUserByUserIdResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FindUserByUserId", ReplyAction:="*")>  _
        Function FindUserByUserId(ByVal request As SsoUserManagement.FindUserByUserIdRequest) As SsoUserManagement.FindUserByUserIdResponse
        
        'CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRolesByLogin", ReplyAction:="*")>  _
        Function GetRolesByLogin(ByVal request As SsoUserManagement.GetRolesByLoginRequest) As SsoUserManagement.GetRolesByLoginResponse
        
        'CODEGEN: Generating message contract since element name systemId from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRolesBySystem", ReplyAction:="*")>  _
        Function GetRolesBySystem(ByVal request As SsoUserManagement.GetRolesBySystemRequest) As SsoUserManagement.GetRolesBySystemResponse
        
        'CODEGEN: Generating message contract since element name roleName from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CheckRoleExists", ReplyAction:="*")>  _
        Function CheckRoleExists(ByVal request As SsoUserManagement.CheckRoleExistsRequest) As SsoUserManagement.CheckRoleExistsResponse
        
        'CODEGEN: Generating message contract since element name GetOnePointFiveUserResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetOnePointFiveUser", ReplyAction:="*")>  _
        Function GetOnePointFiveUser(ByVal request As SsoUserManagement.GetOnePointFiveUserRequest) As SsoUserManagement.GetOnePointFiveUserResponse
        
        'CODEGEN: Generating message contract since element name GetUserByTokenIdResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUserByTokenId", ReplyAction:="*")>  _
        Function GetUserByTokenId(ByVal request As SsoUserManagement.GetUserByTokenIdRequest) As SsoUserManagement.GetUserByTokenIdResponse
        
        'CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateUser", ReplyAction:="*")>  _
        Function UpdateUser(ByVal request As SsoUserManagement.UpdateUserRequest) As SsoUserManagement.UpdateUserResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AuthoriseUser", ReplyAction:="*")>  _
        Function AuthoriseUser(ByVal tokenId As System.Guid, ByVal roleId As System.Guid) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LogOut", ReplyAction:="*")>  _
        Function LogOut(ByVal tokenId As System.Guid) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IsUserOnePointFiveAuthenticated", ReplyAction:="*")>  _
        Function IsUserOnePointFiveAuthenticated(ByVal tokenId As System.Guid) As Boolean
        
        'CODEGEN: Generating message contract since element name oldPassword from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ChangePassword", ReplyAction:="*")>  _
        Function ChangePassword(ByVal request As SsoUserManagement.ChangePasswordRequest) As SsoUserManagement.ChangePasswordResponse
        
        'CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ResetPassword", ReplyAction:="*")>  _
        Function ResetPassword(ByVal request As SsoUserManagement.ResetPasswordRequest) As SsoUserManagement.ResetPasswordResponse
        
        'CODEGEN: Generating message contract since element name oldPasscode from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ChangePasscode", ReplyAction:="*")>  _
        Function ChangePasscode(ByVal request As SsoUserManagement.ChangePasscodeRequest) As SsoUserManagement.ChangePasscodeResponse
        
        'CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ResetPasscode", ReplyAction:="*")>  _
        Function ResetPasscode(ByVal request As SsoUserManagement.ResetPasscodeRequest) As SsoUserManagement.ResetPasscodeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetMaxLoginAttempts", ReplyAction:="*")>  _
        Function GetMaxLoginAttempts() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/TestDatabaseAccess", ReplyAction:="*")>  _
        Function TestDatabaseAccess() As Boolean
        
        'CODEGEN: Generating message contract since element name GetMessageResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetMessage", ReplyAction:="*")>  _
        Function GetMessage(ByVal request As SsoUserManagement.GetMessageRequest) As SsoUserManagement.GetMessageResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetUserRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUser", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetUserRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetUserRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetUserRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String)
            MyBase.New
            Me.login = login
            Me.password = password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetUserResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetUserResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetUserResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUserResult As SsoUserManagement.VlaUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUserResult As SsoUserManagement.VlaUser)
            MyBase.New
            Me.GetUserResult = GetUserResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class FindUsersByEmailRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FindUsersByEmail", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.FindUsersByEmailRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.FindUsersByEmailRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class FindUsersByEmailRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public email As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal email As String)
            MyBase.New
            Me.email = email
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class FindUsersByEmailResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FindUsersByEmailResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.FindUsersByEmailResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.FindUsersByEmailResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class FindUsersByEmailResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public FindUsersByEmailResult() As SsoUserManagement.VlaPartialUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FindUsersByEmailResult() As SsoUserManagement.VlaPartialUser)
            MyBase.New
            Me.FindUsersByEmailResult = FindUsersByEmailResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class FindUserByLoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FindUserByLogin", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.FindUserByLoginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.FindUserByLoginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class FindUserByLoginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String)
            MyBase.New
            Me.login = login
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class FindUserByLoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FindUserByLoginResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.FindUserByLoginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.FindUserByLoginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class FindUserByLoginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public FindUserByLoginResult As SsoUserManagement.VlaPartialUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FindUserByLoginResult As SsoUserManagement.VlaPartialUser)
            MyBase.New
            Me.FindUserByLoginResult = FindUserByLoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class FindUserByUserIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FindUserByUserId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.FindUserByUserIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.FindUserByUserIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class FindUserByUserIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public userId As System.Guid
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal userId As System.Guid)
            MyBase.New
            Me.userId = userId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class FindUserByUserIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FindUserByUserIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.FindUserByUserIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.FindUserByUserIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class FindUserByUserIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public FindUserByUserIdResult As SsoUserManagement.VlaPartialUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FindUserByUserIdResult As SsoUserManagement.VlaPartialUser)
            MyBase.New
            Me.FindUserByUserIdResult = FindUserByUserIdResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetRolesByLoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetRolesByLogin", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetRolesByLoginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetRolesByLoginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetRolesByLoginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String)
            MyBase.New
            Me.login = login
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetRolesByLoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetRolesByLoginResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetRolesByLoginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetRolesByLoginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetRolesByLoginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetRolesByLoginResult() As SsoUserManagement.VlaRole
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetRolesByLoginResult() As SsoUserManagement.VlaRole)
            MyBase.New
            Me.GetRolesByLoginResult = GetRolesByLoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetRolesBySystemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetRolesBySystem", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetRolesBySystemRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetRolesBySystemRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetRolesBySystemRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public systemId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal systemId As String)
            MyBase.New
            Me.systemId = systemId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetRolesBySystemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetRolesBySystemResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetRolesBySystemResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetRolesBySystemResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetRolesBySystemResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetRolesBySystemResult() As SsoUserManagement.VlaRole
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetRolesBySystemResult() As SsoUserManagement.VlaRole)
            MyBase.New
            Me.GetRolesBySystemResult = GetRolesBySystemResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class CheckRoleExistsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CheckRoleExists", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.CheckRoleExistsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.CheckRoleExistsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class CheckRoleExistsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public roleName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal roleName As String)
            MyBase.New
            Me.roleName = roleName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class CheckRoleExistsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CheckRoleExistsResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.CheckRoleExistsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.CheckRoleExistsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class CheckRoleExistsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CheckRoleExistsResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CheckRoleExistsResult As Boolean)
            MyBase.New
            Me.CheckRoleExistsResult = CheckRoleExistsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetOnePointFiveUserRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOnePointFiveUser", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetOnePointFiveUserRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetOnePointFiveUserRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetOnePointFiveUserRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public tokenId As System.Guid
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public passcodeChar1 As Char
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public passcodeChar2 As Char
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tokenId As System.Guid, ByVal passcodeChar1 As Char, ByVal passcodeChar2 As Char)
            MyBase.New
            Me.tokenId = tokenId
            Me.passcodeChar1 = passcodeChar1
            Me.passcodeChar2 = passcodeChar2
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetOnePointFiveUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOnePointFiveUserResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetOnePointFiveUserResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetOnePointFiveUserResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetOnePointFiveUserResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetOnePointFiveUserResult As SsoUserManagement.VlaUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetOnePointFiveUserResult As SsoUserManagement.VlaUser)
            MyBase.New
            Me.GetOnePointFiveUserResult = GetOnePointFiveUserResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetUserByTokenIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserByTokenId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetUserByTokenIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetUserByTokenIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetUserByTokenIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public tokenId As System.Guid
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tokenId As System.Guid)
            MyBase.New
            Me.tokenId = tokenId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetUserByTokenIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUserByTokenIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetUserByTokenIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetUserByTokenIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetUserByTokenIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUserByTokenIdResult As SsoUserManagement.VlaUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUserByTokenIdResult As SsoUserManagement.VlaUser)
            MyBase.New
            Me.GetUserByTokenIdResult = GetUserByTokenIdResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class UpdateUserRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateUser", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.UpdateUserRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.UpdateUserRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class UpdateUserRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public user As SsoUserManagement.VlaUser
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal user As SsoUserManagement.VlaUser)
            MyBase.New
            Me.user = user
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class UpdateUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateUserResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.UpdateUserResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.UpdateUserResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class UpdateUserResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public UpdateUserResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateUserResult As Boolean)
            MyBase.New
            Me.UpdateUserResult = UpdateUserResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ChangePasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ChangePassword", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ChangePasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ChangePasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ChangePasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public userId As System.Guid
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public oldPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public newPassword As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal userId As System.Guid, ByVal oldPassword As String, ByVal newPassword As String)
            MyBase.New
            Me.userId = userId
            Me.oldPassword = oldPassword
            Me.newPassword = newPassword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ChangePasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ChangePasswordResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ChangePasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ChangePasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ChangePasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ChangePasswordResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ChangePasswordResult As Boolean)
            MyBase.New
            Me.ChangePasswordResult = ChangePasswordResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ResetPasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ResetPassword", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ResetPasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ResetPasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ResetPasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String)
            MyBase.New
            Me.login = login
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ResetPasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ResetPasswordResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ResetPasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ResetPasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ResetPasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ResetPasswordResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ResetPasswordResult As Boolean)
            MyBase.New
            Me.ResetPasswordResult = ResetPasswordResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ChangePasscodeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ChangePasscode", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ChangePasscodeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ChangePasscodeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ChangePasscodeRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public userId As System.Guid
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public oldPasscode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public newPasscode As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal userId As System.Guid, ByVal oldPasscode As String, ByVal newPasscode As String)
            MyBase.New
            Me.userId = userId
            Me.oldPasscode = oldPasscode
            Me.newPasscode = newPasscode
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ChangePasscodeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ChangePasscodeResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ChangePasscodeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ChangePasscodeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ChangePasscodeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ChangePasscodeResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ChangePasscodeResult As Boolean)
            MyBase.New
            Me.ChangePasscodeResult = ChangePasscodeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ResetPasscodeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ResetPasscode", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ResetPasscodeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ResetPasscodeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ResetPasscodeRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String)
            MyBase.New
            Me.login = login
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class ResetPasscodeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ResetPasscodeResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.ResetPasscodeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.ResetPasscodeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class ResetPasscodeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ResetPasscodeResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ResetPasscodeResult As Boolean)
            MyBase.New
            Me.ResetPasscodeResult = ResetPasscodeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetMessageRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetMessage", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetMessageRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetMessageRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Friend Class GetMessageRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Friend Class GetMessageResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetMessageResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As SsoUserManagement.GetMessageResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SsoUserManagement.GetMessageResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Friend Class GetMessageResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetMessageResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetMessageResult As String)
            MyBase.New
            Me.GetMessageResult = GetMessageResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface ServiceSoapChannel
        Inherits SsoUserManagement.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of SsoUserManagement.ServiceSoap)
        Implements SsoUserManagement.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_GetUser(ByVal request As SsoUserManagement.GetUserRequest) As SsoUserManagement.GetUserResponse Implements SsoUserManagement.ServiceSoap.GetUser
            Return MyBase.Channel.GetUser(request)
        End Function
        
        Public Function GetUser(ByVal login As String, ByVal password As String) As SsoUserManagement.VlaUser
            Dim inValue As SsoUserManagement.GetUserRequest = New SsoUserManagement.GetUserRequest()
            inValue.Body = New SsoUserManagement.GetUserRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            Dim retVal As SsoUserManagement.GetUserResponse = CType(Me,SsoUserManagement.ServiceSoap).GetUser(inValue)
            Return retVal.Body.GetUserResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_FindUsersByEmail(ByVal request As SsoUserManagement.FindUsersByEmailRequest) As SsoUserManagement.FindUsersByEmailResponse Implements SsoUserManagement.ServiceSoap.FindUsersByEmail
            Return MyBase.Channel.FindUsersByEmail(request)
        End Function
        
        Public Function FindUsersByEmail(ByVal email As String) As SsoUserManagement.VlaPartialUser()
            Dim inValue As SsoUserManagement.FindUsersByEmailRequest = New SsoUserManagement.FindUsersByEmailRequest()
            inValue.Body = New SsoUserManagement.FindUsersByEmailRequestBody()
            inValue.Body.email = email
            Dim retVal As SsoUserManagement.FindUsersByEmailResponse = CType(Me,SsoUserManagement.ServiceSoap).FindUsersByEmail(inValue)
            Return retVal.Body.FindUsersByEmailResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_FindUserByLogin(ByVal request As SsoUserManagement.FindUserByLoginRequest) As SsoUserManagement.FindUserByLoginResponse Implements SsoUserManagement.ServiceSoap.FindUserByLogin
            Return MyBase.Channel.FindUserByLogin(request)
        End Function
        
        Public Function FindUserByLogin(ByVal login As String) As SsoUserManagement.VlaPartialUser
            Dim inValue As SsoUserManagement.FindUserByLoginRequest = New SsoUserManagement.FindUserByLoginRequest()
            inValue.Body = New SsoUserManagement.FindUserByLoginRequestBody()
            inValue.Body.login = login
            Dim retVal As SsoUserManagement.FindUserByLoginResponse = CType(Me,SsoUserManagement.ServiceSoap).FindUserByLogin(inValue)
            Return retVal.Body.FindUserByLoginResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_FindUserByUserId(ByVal request As SsoUserManagement.FindUserByUserIdRequest) As SsoUserManagement.FindUserByUserIdResponse Implements SsoUserManagement.ServiceSoap.FindUserByUserId
            Return MyBase.Channel.FindUserByUserId(request)
        End Function
        
        Public Function FindUserByUserId(ByVal userId As System.Guid) As SsoUserManagement.VlaPartialUser
            Dim inValue As SsoUserManagement.FindUserByUserIdRequest = New SsoUserManagement.FindUserByUserIdRequest()
            inValue.Body = New SsoUserManagement.FindUserByUserIdRequestBody()
            inValue.Body.userId = userId
            Dim retVal As SsoUserManagement.FindUserByUserIdResponse = CType(Me,SsoUserManagement.ServiceSoap).FindUserByUserId(inValue)
            Return retVal.Body.FindUserByUserIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_GetRolesByLogin(ByVal request As SsoUserManagement.GetRolesByLoginRequest) As SsoUserManagement.GetRolesByLoginResponse Implements SsoUserManagement.ServiceSoap.GetRolesByLogin
            Return MyBase.Channel.GetRolesByLogin(request)
        End Function
        
        Public Function GetRolesByLogin(ByVal login As String) As SsoUserManagement.VlaRole()
            Dim inValue As SsoUserManagement.GetRolesByLoginRequest = New SsoUserManagement.GetRolesByLoginRequest()
            inValue.Body = New SsoUserManagement.GetRolesByLoginRequestBody()
            inValue.Body.login = login
            Dim retVal As SsoUserManagement.GetRolesByLoginResponse = CType(Me,SsoUserManagement.ServiceSoap).GetRolesByLogin(inValue)
            Return retVal.Body.GetRolesByLoginResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_GetRolesBySystem(ByVal request As SsoUserManagement.GetRolesBySystemRequest) As SsoUserManagement.GetRolesBySystemResponse Implements SsoUserManagement.ServiceSoap.GetRolesBySystem
            Return MyBase.Channel.GetRolesBySystem(request)
        End Function
        
        Public Function GetRolesBySystem(ByVal systemId As String) As SsoUserManagement.VlaRole()
            Dim inValue As SsoUserManagement.GetRolesBySystemRequest = New SsoUserManagement.GetRolesBySystemRequest()
            inValue.Body = New SsoUserManagement.GetRolesBySystemRequestBody()
            inValue.Body.systemId = systemId
            Dim retVal As SsoUserManagement.GetRolesBySystemResponse = CType(Me,SsoUserManagement.ServiceSoap).GetRolesBySystem(inValue)
            Return retVal.Body.GetRolesBySystemResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_CheckRoleExists(ByVal request As SsoUserManagement.CheckRoleExistsRequest) As SsoUserManagement.CheckRoleExistsResponse Implements SsoUserManagement.ServiceSoap.CheckRoleExists
            Return MyBase.Channel.CheckRoleExists(request)
        End Function
        
        Public Function CheckRoleExists(ByVal roleName As String) As Boolean
            Dim inValue As SsoUserManagement.CheckRoleExistsRequest = New SsoUserManagement.CheckRoleExistsRequest()
            inValue.Body = New SsoUserManagement.CheckRoleExistsRequestBody()
            inValue.Body.roleName = roleName
            Dim retVal As SsoUserManagement.CheckRoleExistsResponse = CType(Me,SsoUserManagement.ServiceSoap).CheckRoleExists(inValue)
            Return retVal.Body.CheckRoleExistsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_GetOnePointFiveUser(ByVal request As SsoUserManagement.GetOnePointFiveUserRequest) As SsoUserManagement.GetOnePointFiveUserResponse Implements SsoUserManagement.ServiceSoap.GetOnePointFiveUser
            Return MyBase.Channel.GetOnePointFiveUser(request)
        End Function
        
        Public Function GetOnePointFiveUser(ByVal tokenId As System.Guid, ByVal passcodeChar1 As Char, ByVal passcodeChar2 As Char) As SsoUserManagement.VlaUser
            Dim inValue As SsoUserManagement.GetOnePointFiveUserRequest = New SsoUserManagement.GetOnePointFiveUserRequest()
            inValue.Body = New SsoUserManagement.GetOnePointFiveUserRequestBody()
            inValue.Body.tokenId = tokenId
            inValue.Body.passcodeChar1 = passcodeChar1
            inValue.Body.passcodeChar2 = passcodeChar2
            Dim retVal As SsoUserManagement.GetOnePointFiveUserResponse = CType(Me,SsoUserManagement.ServiceSoap).GetOnePointFiveUser(inValue)
            Return retVal.Body.GetOnePointFiveUserResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_GetUserByTokenId(ByVal request As SsoUserManagement.GetUserByTokenIdRequest) As SsoUserManagement.GetUserByTokenIdResponse Implements SsoUserManagement.ServiceSoap.GetUserByTokenId
            Return MyBase.Channel.GetUserByTokenId(request)
        End Function
        
        Public Function GetUserByTokenId(ByVal tokenId As System.Guid) As SsoUserManagement.VlaUser
            Dim inValue As SsoUserManagement.GetUserByTokenIdRequest = New SsoUserManagement.GetUserByTokenIdRequest()
            inValue.Body = New SsoUserManagement.GetUserByTokenIdRequestBody()
            inValue.Body.tokenId = tokenId
            Dim retVal As SsoUserManagement.GetUserByTokenIdResponse = CType(Me,SsoUserManagement.ServiceSoap).GetUserByTokenId(inValue)
            Return retVal.Body.GetUserByTokenIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_UpdateUser(ByVal request As SsoUserManagement.UpdateUserRequest) As SsoUserManagement.UpdateUserResponse Implements SsoUserManagement.ServiceSoap.UpdateUser
            Return MyBase.Channel.UpdateUser(request)
        End Function
        
        Public Function UpdateUser(ByVal user As SsoUserManagement.VlaUser) As Boolean
            Dim inValue As SsoUserManagement.UpdateUserRequest = New SsoUserManagement.UpdateUserRequest()
            inValue.Body = New SsoUserManagement.UpdateUserRequestBody()
            inValue.Body.user = user
            Dim retVal As SsoUserManagement.UpdateUserResponse = CType(Me,SsoUserManagement.ServiceSoap).UpdateUser(inValue)
            Return retVal.Body.UpdateUserResult
        End Function
        
        Public Function AuthoriseUser(ByVal tokenId As System.Guid, ByVal roleId As System.Guid) As Boolean Implements SsoUserManagement.ServiceSoap.AuthoriseUser
            Return MyBase.Channel.AuthoriseUser(tokenId, roleId)
        End Function
        
        Public Function LogOut(ByVal tokenId As System.Guid) As Boolean Implements SsoUserManagement.ServiceSoap.LogOut
            Return MyBase.Channel.LogOut(tokenId)
        End Function
        
        Public Function IsUserOnePointFiveAuthenticated(ByVal tokenId As System.Guid) As Boolean Implements SsoUserManagement.ServiceSoap.IsUserOnePointFiveAuthenticated
            Return MyBase.Channel.IsUserOnePointFiveAuthenticated(tokenId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_ChangePassword(ByVal request As SsoUserManagement.ChangePasswordRequest) As SsoUserManagement.ChangePasswordResponse Implements SsoUserManagement.ServiceSoap.ChangePassword
            Return MyBase.Channel.ChangePassword(request)
        End Function
        
        Public Function ChangePassword(ByVal userId As System.Guid, ByVal oldPassword As String, ByVal newPassword As String) As Boolean
            Dim inValue As SsoUserManagement.ChangePasswordRequest = New SsoUserManagement.ChangePasswordRequest()
            inValue.Body = New SsoUserManagement.ChangePasswordRequestBody()
            inValue.Body.userId = userId
            inValue.Body.oldPassword = oldPassword
            inValue.Body.newPassword = newPassword
            Dim retVal As SsoUserManagement.ChangePasswordResponse = CType(Me,SsoUserManagement.ServiceSoap).ChangePassword(inValue)
            Return retVal.Body.ChangePasswordResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_ResetPassword(ByVal request As SsoUserManagement.ResetPasswordRequest) As SsoUserManagement.ResetPasswordResponse Implements SsoUserManagement.ServiceSoap.ResetPassword
            Return MyBase.Channel.ResetPassword(request)
        End Function
        
        Public Function ResetPassword(ByVal login As String) As Boolean
            Dim inValue As SsoUserManagement.ResetPasswordRequest = New SsoUserManagement.ResetPasswordRequest()
            inValue.Body = New SsoUserManagement.ResetPasswordRequestBody()
            inValue.Body.login = login
            Dim retVal As SsoUserManagement.ResetPasswordResponse = CType(Me,SsoUserManagement.ServiceSoap).ResetPassword(inValue)
            Return retVal.Body.ResetPasswordResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_ChangePasscode(ByVal request As SsoUserManagement.ChangePasscodeRequest) As SsoUserManagement.ChangePasscodeResponse Implements SsoUserManagement.ServiceSoap.ChangePasscode
            Return MyBase.Channel.ChangePasscode(request)
        End Function
        
        Public Function ChangePasscode(ByVal userId As System.Guid, ByVal oldPasscode As String, ByVal newPasscode As String) As Boolean
            Dim inValue As SsoUserManagement.ChangePasscodeRequest = New SsoUserManagement.ChangePasscodeRequest()
            inValue.Body = New SsoUserManagement.ChangePasscodeRequestBody()
            inValue.Body.userId = userId
            inValue.Body.oldPasscode = oldPasscode
            inValue.Body.newPasscode = newPasscode
            Dim retVal As SsoUserManagement.ChangePasscodeResponse = CType(Me,SsoUserManagement.ServiceSoap).ChangePasscode(inValue)
            Return retVal.Body.ChangePasscodeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_ResetPasscode(ByVal request As SsoUserManagement.ResetPasscodeRequest) As SsoUserManagement.ResetPasscodeResponse Implements SsoUserManagement.ServiceSoap.ResetPasscode
            Return MyBase.Channel.ResetPasscode(request)
        End Function
        
        Public Function ResetPasscode(ByVal login As String) As Boolean
            Dim inValue As SsoUserManagement.ResetPasscodeRequest = New SsoUserManagement.ResetPasscodeRequest()
            inValue.Body = New SsoUserManagement.ResetPasscodeRequestBody()
            inValue.Body.login = login
            Dim retVal As SsoUserManagement.ResetPasscodeResponse = CType(Me,SsoUserManagement.ServiceSoap).ResetPasscode(inValue)
            Return retVal.Body.ResetPasscodeResult
        End Function
        
        Public Function GetMaxLoginAttempts() As Integer Implements SsoUserManagement.ServiceSoap.GetMaxLoginAttempts
            Return MyBase.Channel.GetMaxLoginAttempts
        End Function
        
        Public Function TestDatabaseAccess() As Boolean Implements SsoUserManagement.ServiceSoap.TestDatabaseAccess
            Return MyBase.Channel.TestDatabaseAccess
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SsoUserManagement_ServiceSoap_GetMessage(ByVal request As SsoUserManagement.GetMessageRequest) As SsoUserManagement.GetMessageResponse Implements SsoUserManagement.ServiceSoap.GetMessage
            Return MyBase.Channel.GetMessage(request)
        End Function
        
        Public Function GetMessage() As String
            Dim inValue As SsoUserManagement.GetMessageRequest = New SsoUserManagement.GetMessageRequest()
            inValue.Body = New SsoUserManagement.GetMessageRequestBody()
            Dim retVal As SsoUserManagement.GetMessageResponse = CType(Me,SsoUserManagement.ServiceSoap).GetMessage(inValue)
            Return retVal.Body.GetMessageResult
        End Function
    End Class
End Namespace
