'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TreeSelection

    '''<summary>
    '''selectedTextContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedTextContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''selectedTextValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedTextValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''removeSelectionButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents removeSelectionButton As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''selectionAnnouncement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectionAnnouncement As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
