

    IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sppPrioritisationCalculation]') AND type in (N'P', N'PC'))
    DROP PROCEDURE [dbo].[sppPrioritisationCalculation]
    GO

    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
    -- =============================================
    --  This stored procedure was autogenerated by the Profiles
    --  CodeGen application on 14/10/2008 16:16:21 .
	  -- =============================================
	  CREATE PROCEDURE sppPrioritisationCalculation
	  @ProfileVersionId uniqueidentifier
	  AS
	  BEGIN
	  -- SET NOCOUNT ON added to prevent extra result sets from
	  -- interfering with SELECT statements.
	  SET NOCOUNT ON;

	  DECLARE @SpeciesId uniqueidentifier

	  DELETE
	  [ProfileVersionSpeciesPrioritisation]
	  WHERE
	  [ProfileVersionId] = @ProfileVersionId

	  DELETE
	  [ProfileVersionPrioritisedSpecies]
	  WHERE
	  [ProfileVersionId] = @ProfileVersionId
	  
	  DECLARE @SpeciesList TABLE
	  (
	  SpeciesId uniqueidentifier
	  )

	  DECLARE csrProfileSpecies CURSOR FOR
	  SELECT
	  [SpeciesId]
	  FROM
	  [ProfileVersionSpecies] INNER JOIN [luAffectedSpeciesType] ON [ProfileVersionSpecies].[AffectedSpeciesTypeId] = [luAffectedSpeciesType].[Id]
	  WHERE
	  [ProfileVersionId] = @ProfileVersionId AND
	  [luAffectedSpeciesType].[Name] = 'Profiled'
	  FOR READ ONLY

	  OPEN csrProfileSpecies

	  FETCH NEXT FROM csrProfileSpecies INTO @SpeciesId

	  WHILE @@FETCH_STATUS = 0 BEGIN

	  INSERT INTO @SpeciesList
	  SELECT
	  [Id]
	  FROM
	  dbo.GetChildSpecies(@SpeciesId)

	  INSERT INTO [ProfileVersionPrioritisedSpecies]
	  SELECT
	  @ProfileVersionId,
	  SpeciesId,
	  @SpeciesId
	  FROM
	  @SpeciesList
	  
	  DECLARE @PrioritisationCriterionValueId uniqueidentifier
	  DECLARE @IsMissing bit

	  
      -- Internationaltrade

			  DECLARE @InternationaltradeIrrelevanceFlag1 uniqueidentifier
						  SELECT
						  @InternationaltradeIrrelevanceFlag1 = [CommercialTrade]
						  FROM
						  [InternationalTradeSpecies]
						  WHERE
						  [ProfileVersionId] = @ProfileVersionId AND
						  [SpeciesId] = @SpeciesId
					  

			  DECLARE @InternationaltradeIrrelevanceFlag2 uniqueidentifier
						  SELECT
						  @InternationaltradeIrrelevanceFlag2 = [RangeOfCommoditiesCompromised]
						  FROM
						  [InternationalTrade]
						  WHERE
						  [ProfileVersionId] = @ProfileVersionId
					  
        --Is there an obligation to control this disease under EU law?
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTrade] INNER JOIN [luStatutoryObligationLevel] ON [InternationalTrade].[StatutoryObligationToControl] = [luStatutoryObligationLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luStatutoryObligationLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'CE0A361A-B998-41E7-B424-0B9AF591D8E8'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'CE0A361A-B998-41E7-B424-0B9AF591D8E8',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Export market value for each species/group
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTradeSpecies] INNER JOIN [luTradeImpactLevel] ON [InternationalTradeSpecies].[ExportMarketValue] = [luTradeImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luTradeImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '4107815A-0E2B-4100-BDC1-4FE44864BBE1'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '4107815A-0E2B-4100-BDC1-4FE44864BBE1',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Annual level of export consignments containing animals/ commodities of this species sent into third country trade
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTradeSpecies] INNER JOIN [luTradeImpactLevel] ON [InternationalTradeSpecies].[ImpactOnThirdCountryFlows] = [luTradeImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luTradeImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '2958D62E-46D6-4793-A889-56668429A7B7'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '2958D62E-46D6-4793-A889-56668429A7B7',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Annual level of export consignments containing animals/ commodities of this species sent into intracommunity trade
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTradeSpecies] INNER JOIN [luTradeImpactLevel] ON [InternationalTradeSpecies].[ImpactOnIntraCommunityFlows] = [luTradeImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luTradeImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '2B4E7E02-09A6-4368-AA9D-7E6D442A040C'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '2B4E7E02-09A6-4368-AA9D-7E6D442A040C',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Resource and time required to re-establish intra-community trading status
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTrade] INNER JOIN [luImpactLevel] ON [InternationalTrade].[ReestablishmentOfTradingStatus] = [luImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '53A30261-2C7B-4159-9E9D-B29564302AC9'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '53A30261-2C7B-4159-9E9D-B29564302AC9',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Potential for restricting impact on exports to third countries by regionalisation/zoning or compartmentalisation
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTrade] INNER JOIN [luRegionalisationLevel] ON [InternationalTrade].[PotentialForRegionalisation] = [luRegionalisationLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luRegionalisationLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'C89EDC33-118D-42C7-B917-D472F1C7F317'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'C89EDC33-118D-42C7-B917-D472F1C7F317',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact of this disease on the breadth of trade in animals and animal products (live animals and/or products)
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTrade] INNER JOIN [luCommoditiesCompromisedLevel] ON [InternationalTrade].[RangeOfCommoditiesCompromised] = [luCommoditiesCompromisedLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luCommoditiesCompromisedLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '91CD55C3-B98F-4A62-A17F-DD36945D2E5C'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '91CD55C3-B98F-4A62-A17F-DD36945D2E5C',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Relative importance of export trade to the industry sector
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [InternationalTradeSpecies] INNER JOIN [luTradeImpactLevel] ON [InternationalTradeSpecies].[ImportanceOfExportTrade] = [luTradeImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luTradeImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '0B81298D-F3D9-4CDA-80D8-F6BFC728A42D'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag1 IS NOT NULL
		
			AND @InternationaltradeIrrelevanceFlag2 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@InternationaltradeIrrelevanceFlag1 = '5D3B5094-2432-47C5-B3B0-B15E317FB5D6'
				OR 
					@InternationaltradeIrrelevanceFlag2 = 'C7813A45-947D-486B-BE8A-914357F3F0E0'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '0B81298D-F3D9-4CDA-80D8-F6BFC728A42D',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
      -- Publichealth

			  DECLARE @PublichealthIrrelevanceFlag1 uniqueidentifier
						  SELECT
						  @PublichealthIrrelevanceFlag1 = [ZoonoticIndicator]
						  FROM
						  [HumanHealth]
						  WHERE
						  [ProfileVersionId] = @ProfileVersionId
					  
        --Likelihood of serious human morbidity
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealth] INNER JOIN [luMaximumSeverityLevel] ON [HumanHealth].[MaximumSeverityOfHumanDisease] = [luMaximumSeverityLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luMaximumSeverityLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '198722DD-F904-4DA7-9CA2-0620B5EA82C2'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '198722DD-F904-4DA7-9CA2-0620B5EA82C2',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Level of human-animal (or products) interaction/ exposure
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealthSpecies] INNER JOIN [luExposureLevel] ON [HumanHealthSpecies].[LevelOfHumanExposureToAnimalOrProducts] = [luExposureLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luExposureLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'AD720108-03B7-44FA-9F74-1B5C2B0F0D8E'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'AD720108-03B7-44FA-9F74-1B5C2B0F0D8E',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Uncertainty: Assessment of the current state of knowledge of the public health significance of this infection or issue
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealth] INNER JOIN [luUncertaintyLevel] ON [HumanHealth].[Uncertainty] = [luUncertaintyLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luUncertaintyLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '0202D258-B3E4-4C8C-9777-3856CEDAFEA9'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '0202D258-B3E4-4C8C-9777-3856CEDAFEA9',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Transmissibility between humans in GB society
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealth] INNER JOIN [luTransmissibilityIndicator] ON [HumanHealth].[TransmissibilityIndicator] = [luTransmissibilityIndicator].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luTransmissibilityIndicator].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'FBDBB16A-94CF-43B2-A664-678B628BBB52'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'FBDBB16A-94CF-43B2-A664-678B628BBB52',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Average cost per case
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealth] INNER JOIN [luCostLevel] ON [HumanHealth].[AverageCostPerCase] = [luCostLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luCostLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '39E305D8-7CB0-4F6D-9E88-822A622C0C1D'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '39E305D8-7CB0-4F6D-9E88-822A622C0C1D',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Modal severity of human disease
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealth] INNER JOIN [luModalSeverityLevel] ON [HumanHealth].[ModalSeverityOfHumanDisease] = [luModalSeverityLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luModalSeverityLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '36D7A0BD-FD41-4046-9531-B935EEC6A16D'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '36D7A0BD-FD41-4046-9531-B935EEC6A16D',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Proportion of human cases in GB attributable to exposure to animals or animal products from GB
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealthSpecies] INNER JOIN [luAttributableFraction] ON [HumanHealthSpecies].[AttributableFraction] = [luAttributableFraction].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luAttributableFraction].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'BC4C9E3A-39D6-44BE-8CB3-BE4A5FAC6DDD'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'BC4C9E3A-39D6-44BE-8CB3-BE4A5FAC6DDD',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Annual number of human cases of the disease in GB
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealth] INNER JOIN [luHumanCasesLevel] ON [HumanHealth].[AnnualNumberOfHumanCasesInGB] = [luHumanCasesLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luHumanCasesLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '4E481036-517F-4F31-9C45-CFCB1DF23BC3'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '4E481036-517F-4F31-9C45-CFCB1DF23BC3',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Indirect economic costs of human illness
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [HumanHealth] INNER JOIN [luCostLevel] ON [HumanHealth].[IndirectEconomicCostOfHumanIllness] = [luCostLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luCostLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '6E223561-31D8-466A-8714-D990CFE63A1A'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @PublichealthIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@PublichealthIrrelevanceFlag1 = 'CBB4614A-4964-4CD1-8859-829D08CA3DFB'
				 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '6E223561-31D8-466A-8714-D990CFE63A1A',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
      -- Riskandepidemiology
        --Uptake of control measures applied at the holding level by keepers of this species
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [ApproachToControlSpecies] INNER JOIN [luImpactLevel] ON [ApproachToControlSpecies].[UptakeAtHoldingLevel] = [luImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'B88F4BF0-3C2A-48AC-822C-0189C87B9C5B'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'B88F4BF0-3C2A-48AC-822C-0189C87B9C5B',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Rate of spread on and between affected premises
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [EpidemiologySpecies] INNER JOIN [luSpreadRateLevel] ON [EpidemiologySpecies].[RateOfSpreadOnPremises] = [luSpreadRateLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luSpreadRateLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '93FE637F-B831-4132-8A6B-1F71B803748A'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '93FE637F-B831-4132-8A6B-1F71B803748A',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Is there a reservoir in GB for this disease/agent in another species or vector
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [EpidemiologySpecies] INNER JOIN [luWildlifeReservoirIndicator] ON [EpidemiologySpecies].[WildlifeReservoirIndicator] = [luWildlifeReservoirIndicator].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luWildlifeReservoirIndicator].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'BA7F975A-684A-4148-8B2D-3A76DEDA3524'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'BA7F975A-684A-4148-8B2D-3A76DEDA3524',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Current holding level prevalence / Risk of introduction into animals in GB
        DECLARE @RE01MappingFlag bit
        
          
                SELECT
                @RE01MappingFlag = [GBPresenceIndicator]
                FROM
                [GeographicDistribution]
                WHERE
                [ProfileVersionId] = @ProfileVersionId
              

          IF @RE01MappingFlag = 1 BEGIN
        
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [GeographicDistribution] INNER JOIN [luPrevalenceLevel] ON [GeographicDistribution].[CurrentPrevalenceInGB] = [luPrevalenceLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luPrevalenceLevel].[LookupValue] = LEFT([PrioritisationCriterionValue].[CriterionValue], LEN([luPrevalenceLevel].[LookupValue]))
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '09322102-9D62-4663-924D-5E70CDC1A8DD'
            
			END

			IF @RE01MappingFlag = 0 BEGIN

		
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [GeographicDistribution] INNER JOIN [luRiskLevel] ON [GeographicDistribution].[RiskOfIntroductionToGB] = [luRiskLevel].[Id]
              INNER JOIN [PrioritisationCriterionValue] ON [luRiskLevel].[LookupValue] = RIGHT([PrioritisationCriterionValue].[CriterionValue], LEN([luRiskLevel].[LookupValue]))
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '09322102-9D62-4663-924D-5E70CDC1A8DD'
            
          
          END
          
        

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '09322102-9D62-4663-924D-5E70CDC1A8DD',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Potential for silent spread
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [EpidemiologySpecies] INNER JOIN [luImpactLevel] ON [EpidemiologySpecies].[PotentialForSilentSpread] = [luImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '4CE1B0C9-F26B-4C92-B6B1-7C380A509966'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '4CE1B0C9-F26B-4C92-B6B1-7C380A509966',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Level of national preparedness or level of implementation for endemics/welfare issues
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [ApproachToControlSpecies] INNER JOIN [luImpactLevel] ON [ApproachToControlSpecies].[LevelOfNationalPreparedness] = [luImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'A3D947FA-2935-4AEE-96B0-A0AE6461C213'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'A3D947FA-2935-4AEE-96B0-A0AE6461C213',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Potential for risk change in animals in GB
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [GeographicDistributionSpecies] INNER JOIN [luRiskChange] ON [GeographicDistributionSpecies].[PotentialForRiskChange] = [luRiskChange].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luRiskChange].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'EFAA8531-EFE7-4CF0-A4B9-A3F507F58FF1'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'EFAA8531-EFE7-4CF0-A4B9-A3F507F58FF1',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Efficacy and practicality of control applied at the holding level
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [ApproachToControlSpecies] INNER JOIN [luImpactLevel] ON [ApproachToControlSpecies].[ControlsAtTheHoldingLevel] = [luImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '5F1196DB-7CC8-45DB-93AB-AFD355DF841C'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '5F1196DB-7CC8-45DB-93AB-AFD355DF841C',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Efficacy of control measures to prevent dissemination in or between animals that are implemented above holding level
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [ApproachToControl] INNER JOIN [luImpactLevel] ON [ApproachToControl].[ControlsAboveTheHoldingLevel] = [luImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'D5E06EA0-8917-427C-81D1-DA362A557433'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'D5E06EA0-8917-427C-81D1-DA362A557433',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
      -- Welfare

			  DECLARE @WelfareIrrelevanceFlag1 bit
						  SELECT
						  @WelfareIrrelevanceFlag1 = [WelfareIssueIndicator]
						  FROM
						  [AnimalWelfareSpecies]
						  WHERE
						  [ProfileVersionId] = @ProfileVersionId AND
						  [SpeciesId] = @SpeciesId
					  
        --Number of clinical cases, at the modal severity, per year in GB
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [GeographicDistributionSpecies] INNER JOIN [luCasesPerYear] ON [GeographicDistributionSpecies].[NumberOfCasesPerYearInGB] = [luCasesPerYear].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luCasesPerYear].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '4A685626-A7D4-4F81-BBC3-08F6E6C32003'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '4A685626-A7D4-4F81-BBC3-08F6E6C32003',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on freedom to express normal behaviour
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [AnimalWelfareSpecies] INNER JOIN [luIssueExtent] ON [AnimalWelfareSpecies].[FreedomToExpressNormalBehaviour] = [luIssueExtent].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luIssueExtent].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'DBA652AB-BB4F-457E-8FBE-2C9109DD7E93'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'DBA652AB-BB4F-457E-8FBE-2C9109DD7E93',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Welfare impact of likely or statutory control measures
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [ApproachToControlSpecies] INNER JOIN [luProportionLevel] ON [ApproachToControlSpecies].[WelfareEffect] = [luProportionLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luProportionLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'A14298BB-3C16-4DC1-94B7-3FB74F0ACDED'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'A14298BB-3C16-4DC1-94B7-3FB74F0ACDED',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Modal duration of welfare impact experienced by animals in GB
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [EpidemiologySpecies] INNER JOIN [luDiseaseDuration] ON [EpidemiologySpecies].[DurationOfDisease] = [luDiseaseDuration].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luDiseaseDuration].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '0F127948-F0DD-4540-A011-48566EEC43DF'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '0F127948-F0DD-4540-A011-48566EEC43DF',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on freedom from fear and distress
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [AnimalWelfareSpecies] INNER JOIN [luIssueExtent] ON [AnimalWelfareSpecies].[FreedomFromFearAndDistress] = [luIssueExtent].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luIssueExtent].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '9E6AEB40-D8EF-485A-B226-50B8F82FE66E'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '9E6AEB40-D8EF-485A-B226-50B8F82FE66E',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on freedom from hunger and thirst
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [AnimalWelfareSpecies] INNER JOIN [luIssueExtent] ON [AnimalWelfareSpecies].[FreedomFromHungerAndThirst] = [luIssueExtent].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luIssueExtent].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '1C3EFE14-25EF-4546-92D5-C0BE3CF236E6'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '1C3EFE14-25EF-4546-92D5-C0BE3CF236E6',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on freedom from discomfort
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [AnimalWelfareSpecies] INNER JOIN [luIssueExtent] ON [AnimalWelfareSpecies].[FreedomFromDiscomfort] = [luIssueExtent].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luIssueExtent].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '7FD01EED-AFD3-445F-ABDC-CC36958D5EE8'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '7FD01EED-AFD3-445F-ABDC-CC36958D5EE8',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Proportion of infected and/or affected animals affected suffering more severely than the mode
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [AnimalWelfareSpecies] INNER JOIN [luProportionLevel] ON [AnimalWelfareSpecies].[ProportionOfAnimalsAffectedSufferingSeverely] = [luProportionLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luProportionLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'DD8A4657-A00F-45D7-B861-DC661411D5BE'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'DD8A4657-A00F-45D7-B861-DC661411D5BE',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on freedom from pain, injury or disease
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [AnimalWelfareSpecies] INNER JOIN [luIssueExtent] ON [AnimalWelfareSpecies].[FreedomFromPainOrInjury] = [luIssueExtent].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luIssueExtent].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'E3AD25B3-5969-4532-9A33-EE7A4D3EBB95'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		
			AND @WelfareIrrelevanceFlag1 IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  
			  IF 
					@WelfareIrrelevanceFlag1 = 0 BEGIN
			  SET @PrioritisationCriterionValueId = NULL
			  SET @IsMissing = 0
			  END
		

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'E3AD25B3-5969-4532-9A33-EE7A4D3EBB95',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
      -- Widersociety
        --Impact on the wider rural community
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [WiderSociety] INNER JOIN [luMortalityLevel] ON [WiderSociety].[WiderRuralCommunity] = [luMortalityLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luMortalityLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '649082D2-788F-4F41-A623-3C2A4E1B39AB'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '649082D2-788F-4F41-A623-3C2A4E1B39AB',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Total potential unplanned cost to exchequer
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [WiderSociety] INNER JOIN [luUnplannedCostLevel] ON [WiderSociety].[PotentialUnplannedCostToExchequer] = [luUnplannedCostLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luUnplannedCostLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '35891467-E5C6-4DC7-9FA8-464F9F26ED7B'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '35891467-E5C6-4DC7-9FA8-464F9F26ED7B',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on the global environment
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [WiderSociety] INNER JOIN [luGlobalEnvironmentImpactLevel] ON [WiderSociety].[GlobalEnvironment] = [luGlobalEnvironmentImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luGlobalEnvironmentImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '11DECCAF-0945-4F7B-BD49-725854B3F1AF'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '11DECCAF-0945-4F7B-BD49-725854B3F1AF',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on the local environment
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [WiderSociety] INNER JOIN [luLocalEnvironmentImpactLevel] ON [WiderSociety].[LocalEnvironment] = [luLocalEnvironmentImpactLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luLocalEnvironmentImpactLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = '4A63BB0A-BE4E-4E03-A81A-BAF0598DA920'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  '4A63BB0A-BE4E-4E03-A81A-BAF0598DA920',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  
        --Impact on the sector that produces this species
              SELECT
              @PrioritisationCriterionValueId = [PrioritisationCriterionValue].[Id]
              FROM
              [WiderSocietySpecies] INNER JOIN [luMortalityLevel] ON [WiderSocietySpecies].[LocalAgriculturalEconomy] = [luMortalityLevel].[Id]
              
                  INNER JOIN [PrioritisationCriterionValue] ON [luMortalityLevel].[LookupValue] = [PrioritisationCriterionValue].[CriterionValue]
                
              WHERE
              [ProfileVersionId] = @ProfileVersionId AND
              [SpeciesId] = @SpeciesId AND
              [PrioritisationCriterionValue].[PrioritisationCriterionId] = 'E892598B-F369-4EC0-9C53-FBEB87F3745F'
            

		  IF 
		@PrioritisationCriterionValueId IS NOT NULL
		 BEGIN
		  SET @IsMissing = 0
		  END ELSE BEGIN
		  SET @IsMissing = 1
		  END
		  		  
		  

		  INSERT INTO [ProfileVersionSpeciesPrioritisation]
		  (
		  [ProfileVersionId],
		  [SpeciesId],
		  [PrioritisationCriterionId],
		  [PrioritisationCriterionValueId],
		  [IsMissing]
		  )
		  SELECT
		  @ProfileVersionId,
		  [SpeciesId],
		  'E892598B-F369-4EC0-9C53-FBEB87F3745F',
		  @PrioritisationCriterionValueId,
		  @IsMissing
		  FROM
		  @SpeciesList

		  SET @PrioritisationCriterionValueId = NULL

	  

    DELETE FROM @SpeciesList
    
    FETCH NEXT FROM csrProfileSpecies INTO @SpeciesId

    END

    CLOSE csrProfileSpecies
    DEALLOCATE csrProfileSpecies

    END
    GO

    GRANT EXECUTE ON [dbo].[sppPrioritisationCalculation] TO [VLAProfilesUser]
    GO
    
  