'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AffectedSpeciesSelector

    '''<summary>
    '''litWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litWarning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''valProfiledSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valProfiledSpecies As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''profiledSpeciesTreeToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profiledSpeciesTreeToggle As Global.Profiles.Web.TreeViewToggleButton

    '''<summary>
    '''tvwProfiledSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvwProfiledSpecies As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''profiledSpeciesSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profiledSpeciesSelected As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''otherAffectedSpeciesTreeToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents otherAffectedSpeciesTreeToggle As Global.Profiles.Web.TreeViewToggleButton

    '''<summary>
    '''tvwOtherAffectedSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvwOtherAffectedSpecies As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''otherAffectedSpeciesSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents otherAffectedSpeciesSelected As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
