'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompareProfileVersions

    '''<summary>
    '''MainUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SelectionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectionPanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''FirstCheckedNodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstCheckedNodeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SecondCheckedNodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecondCheckedNodeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RemoveSelectionButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RemoveSelectionButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TreePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnToggleAllButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToggleAllButton As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''toggleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents toggleText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''treeStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents treeStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tvwProfileVersions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvwProfileVersions As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''ComparePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComparePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnCompare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompare As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cvInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvInput As Global.System.Web.UI.WebControls.CustomValidator
End Class
