'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DiseaseRanking

    '''<summary>
    '''dsDiseaseReferenceTableInfoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDiseaseReferenceTableInfoList As Global.Csla.Web.CslaDataSource

    '''<summary>
    '''ddlDiseaseRankingReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDiseaseRankingReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnEditFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditFilters As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlDiseaseRankingRFIReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDiseaseRankingRFIReport As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnEditRFIFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditRFIFilters As Global.System.Web.UI.WebControls.Button
End Class
