'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditProfileReviewComments

	'''<summary>
	'''tabStrip control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tabStrip As Global.Profiles.WebControls.Profiles.WebControls.TabStrip

	'''<summary>
	'''panReviewComments control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panReviewComments As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''valReviewCommentsSummary control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valReviewCommentsSummary As Global.System.Web.UI.WebControls.ValidationSummary

	'''<summary>
	'''lblErrorReviewComments control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErrorReviewComments As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblAddReviewComments control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAddReviewComments As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnNewReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnNewReviewComment As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''PaginatorPageSize control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PaginatorPageSize As Global.Profiles.Web.PaginatorPageSize

	'''<summary>
	'''grdReviewComments control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdReviewComments As Global.Profiles.WebControls.Profiles.WebControls.GridViewExternalPaging

	'''<summary>
	'''bottomPaginator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents bottomPaginator As Global.Profiles.Web.Paginator

	'''<summary>
	'''pnlViewReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlViewReviewComment As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblViewPanelHeader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblViewPanelHeader As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''litCommentSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litCommentSubject As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litCommentReference control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litCommentReference As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litComment As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''btnReplyReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnReplyReviewComment As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnEditReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnEditReviewComment As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnDeleteReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDeleteReviewComment As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCloseReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCloseReviewComment As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlReviewComment As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblPanelHeader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPanelHeader As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblCommentSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCommentSubject As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''valCommentSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valCommentSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''valCommentSubjectMaxLength control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valCommentSubjectMaxLength As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''txtCommentSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCommentSubject As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblCommentReference control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCommentReference As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''valCommentReference control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valCommentReference As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''valCommentReferenceMaxLength control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valCommentReferenceMaxLength As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''txtCommentReference control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCommentReference As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblCommentComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCommentComment As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''valComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valComment As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''txtComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''spellUserGuidance control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spellUserGuidance As Global.Profiles.WebControls.Profiles.WebControls.SpellCheck

	'''<summary>
	'''btnSaveReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSaveReviewComment As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCancelReviewComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCancelReviewComment As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''dsReviewCommentList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dsReviewCommentList As Global.Csla.Web.CslaDataSource

	'''<summary>
	'''SectionPagination control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SectionPagination As Global.Profiles.Web.SectionPagination
End Class
