'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditProfileFurtherInformation

    '''<summary>
    '''tabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabStrip As Global.Profiles.WebControls.Profiles.WebControls.TabStrip

    '''<summary>
    '''panFurtherInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panFurtherInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''valNoteErrorSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNoteErrorSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''lblNoteError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoteError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlEditNoteUI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEditNoteUI As Global.Profiles.Web.EditNoteUI

    '''<summary>
    '''SectionPagination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SectionPagination As Global.Profiles.Web.SectionPagination
End Class
