'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditDiseaseRankingFilters

    '''<summary>
    '''btnDiseaseRankingFish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiseaseRankingFish As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDiseaseRankingTerrestrial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiseaseRankingTerrestrial As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''drpDiseaseRanking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDiseaseRanking As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlSelectionFilterArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectionFilterArea As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''speciesFilterButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents speciesFilterButton As Global.Profiles.Web.Accordion

    '''<summary>
    '''spsSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spsSelector As Global.Profiles.Web.SpeciesSelector

    '''<summary>
    '''txtDiseaseText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiseaseText As Global.Profiles.WebControls.Profiles.WebControls.ValidatableHiddenField

    '''<summary>
    '''valDiseaseTextRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valDiseaseTextRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblAffectedSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAffectedSpecies As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rdBtnFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdBtnFirst As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''valFirstRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFirstRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rdBtnSecond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdBtnSecond As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''valSecondRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSecondRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rdBtnThird control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdBtnThird As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''valThirdRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valThirdRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rdBtnFourth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdBtnFourth As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''valFourthRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valFourthRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''chkLstTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLstTypes As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ctmLstTypeRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctmLstTypeRequired As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnSaveFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfFNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFNum As Global.System.Web.UI.WebControls.HiddenField
End Class
