'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditProfileReferences

    '''<summary>
    '''tabStrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabStrip As Global.Profiles.WebControls.Profiles.WebControls.TabStrip

    '''<summary>
    '''panReferences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panReferences As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''valNoteSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNoteSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''lblNoteError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoteError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlEditNoteUISciRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEditNoteUISciRef As Global.Profiles.Web.EditNoteUI

    '''<summary>
    '''ctlEditNoteUILegRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlEditNoteUILegRef As Global.Profiles.Web.EditNoteUI

    '''<summary>
    '''SectionPagination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SectionPagination As Global.Profiles.Web.SectionPagination
End Class
