'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Footer

	'''<summary>
	'''litBackToTop control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litBackToTop As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''pnlUserAdmin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlUserAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''litMaintainGlobalUsers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litMaintainGlobalUsers As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litMaintainExternalUsers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litMaintainExternalUsers As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''pnlCrossProfileAdmin control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlCrossProfileAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''litMaintainReferenceData control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litMaintainReferenceData As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litPrioritisationVariables control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litPrioritisationVariables As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''litCrossCuttingIssueScores control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litCrossCuttingIssueScores As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''pnlHelpAndSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlHelpAndSupport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''litUserManuals control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litUserManuals As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''qualityStatementLink control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents qualityStatementLink As Global.System.Web.UI.WebControls.HyperLink
End Class
