'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

	'''<summary>
	'''lstPopularPages control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstPopularPages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''searchPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents searchPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''diseaseRankingLink control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents diseaseRankingLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''staticReportPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents staticReportPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''viewSpeciesDataPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents viewSpeciesDataPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''Image1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

	'''<summary>
	'''helpPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents helpPage As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''maintainProfileVersionPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents maintainProfileVersionPage As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''diseaseRankingFilterPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents diseaseRankingFilterPage As Global.System.Web.UI.WebControls.HyperLink
End Class
