'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MaintainExternalUsers

	'''<summary>
	'''pnlUpdate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlUpdate As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''pnlExternalUsers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlExternalUsers As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''pnlUsersTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlUsersTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''PaginatorPageSize control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PaginatorPageSize As Global.Profiles.Web.PaginatorPageSize

	'''<summary>
	'''grdExternalUsers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdExternalUsers As Global.Profiles.WebControls.Profiles.WebControls.GridViewExternalPaging

	'''<summary>
	'''dsExternalUserList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dsExternalUserList As Global.Csla.Web.CslaDataSource

	'''<summary>
	'''bottomPaginator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents bottomPaginator As Global.Profiles.Web.Paginator

	'''<summary>
	'''pnlProfiles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlProfiles As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblProfileTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblProfileTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''pnlAddProfile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlAddProfile As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlProfileList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlProfileList As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnAddProfile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddProfile As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''PaginatorPageSizeProfileList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PaginatorPageSizeProfileList As Global.Profiles.Web.PaginatorPageSize

	'''<summary>
	'''grdProfileList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdProfileList As Global.Profiles.WebControls.Profiles.WebControls.GridViewExternalPaging

	'''<summary>
	'''bottomPaginatorProfileList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents bottomPaginatorProfileList As Global.Profiles.Web.Paginator

	'''<summary>
	'''pnlProfileButtons control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlProfileButtons As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''chkSubscribeEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkSubscribeEmail As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''btnProfilesOK control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnProfilesOK As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnProfilesCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnProfilesCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''dsProfileList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dsProfileList As Global.Csla.Web.CslaDataSource

	'''<summary>
	'''pnlSections control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlSections As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblSectionTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSectionTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''valSection control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valSection As Global.System.Web.UI.WebControls.ValidationSummary

	'''<summary>
	'''lblRole control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblRole As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlRole control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlRole As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''valRoleDropDown control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valRoleDropDown As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''dsProfileUserRoleList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dsProfileUserRoleList As Global.Csla.Web.CslaDataSource

	'''<summary>
	'''pnlSectionPermissions control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlSectionPermissions As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''valSectionPermissions control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents valSectionPermissions As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''pnlCheckUncheckAll control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlCheckUncheckAll As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''btnCheckAll control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCheckAll As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnUncheckAll control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnUncheckAll As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnSectionOK control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSectionOK As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnSectionCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSectionCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlErrorMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlErrorMessage As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblErrorMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label
End Class
