'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MaintainPrioritisationVariables

    '''<summary>
    '''updatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnCalculateDraftPrioritisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalculateDraftPrioritisation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ltuCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltuCalculate As Global.Profiles.Web.LongTaskUI

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updatePanelPrioritisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updatePanelPrioritisation As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''valsumRankingRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valsumRankingRange As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''txtLowerBound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLowerBound As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rvalLowerBound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvalLowerBound As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''cvalLowerRankingRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvalLowerRankingRange As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''reqvalLowerBound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvalLowerBound As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtUpperBound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUpperBound As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rvalUpperBound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvalUpperBound As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''cvalUpperRankingRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvalUpperRankingRange As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''reqvalUpperBound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqvalUpperBound As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblPrioritisationCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrioritisationCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPrioritisationCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrioritisationCategories As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExportScoreData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportScoreData As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExportAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportAll As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dsPrioritisationCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPrioritisationCategories As Global.Csla.Web.CslaDataSource

    '''<summary>
    '''grdCategoryCriterion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCategoryCriterion As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dsPrioritisationCriterionList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPrioritisationCriterionList As Global.Csla.Web.CslaDataSource

    '''<summary>
    '''pnlCriterionValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCriterionValues As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCriterionCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCriterionCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCriterionIdHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCriterionIdHidden As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''valSummCriterionEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSummCriterionEdit As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''txtCriterionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCriterionName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valCriterionNameReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valCriterionNameReq As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCriterionWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCriterionWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rvalCriterionWeighting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvalCriterionWeighting As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''valCriterionWeightingReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valCriterionWeightingReq As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''grdCriterionValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCriterionValues As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dsPrioritisationCriterionValueList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsPrioritisationCriterionValueList As Global.Csla.Web.CslaDataSource

    '''<summary>
    '''btnSaveCriterion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveCriterion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelCriterion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelCriterion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divPendingChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPendingChanges As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPendingChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendingChanges As Global.System.Web.UI.WebControls.Label
End Class
