'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageProfile

	'''<summary>
	'''lblProfileTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblProfileTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblScenarioTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblScenarioTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblProfilePublicVersion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblProfilePublicVersion As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblProfilePublishedVersion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblProfilePublishedVersion As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lnkAllowPublicAccess control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAllowPublicAccess As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblProfileDraftVersion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblProfileDraftVersion As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlProfileStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlProfileStatus As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lnkProfileProperties control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkProfileProperties As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''lnkMaintainContributors control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkMaintainContributors As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''lnkViewContributorsReport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkViewContributorsReport As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''lnkNewDraftVersion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkNewDraftVersion As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkDelete As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkClone control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkClone As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''lnkCloneScenario control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkCloneScenario As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''lnkPublishPublic control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkPublishPublic As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkPublish control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkPublish As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''ctlInvalidReasonList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctlInvalidReasonList As Global.Profiles.WebControls.Profiles.WebControls.InvalidReasonList

	'''<summary>
	'''dsProfileStatusTypes control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dsProfileStatusTypes As Global.Csla.Web.CslaDataSource

	'''<summary>
	'''lblError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
End Class
