'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NavigationLinks

    '''<summary>
    '''litProfileSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProfileSearch As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCreateProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCreateProfile As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompareProfileVersions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompareProfileVersions As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litReviewTiming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReviewTiming As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litStaticReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litStaticReports As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''litUserGuidance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUserGuidance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''diseaseRankingLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diseaseRankingLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''litViewSpeciesData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litViewSpeciesData As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMaintainSpeciesData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMaintainSpeciesData As Global.System.Web.UI.WebControls.Literal
End Class
