'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NestedProfileQuestions

    '''<summary>
    '''SectionLinksContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SectionLinksContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''ctlSectionLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlSectionLinks As Global.Profiles.Web.ProfileSectionLinks

    '''<summary>
    '''headPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headPageTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NestedProfileContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NestedProfileContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
