'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Notes

    '''<summary>
    '''updNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updNotes As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblNoteType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoteType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlNoteType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNoteType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dsNoteTypeInfoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsNoteTypeInfoList As Global.Csla.Web.CslaDataSource

    '''<summary>
    '''litError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litError As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''divNoteHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNoteHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNoteHeaderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNoteHeaderText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNotes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlAddNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddNote As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAddNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNewNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewNote As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PaginatorPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaginatorPageSize As Global.Profiles.Web.PaginatorPageSize

    '''<summary>
    '''grdNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdNotes As Global.Profiles.WebControls.Profiles.WebControls.GridViewExternalPaging

    '''<summary>
    '''bottomPaginator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottomPaginator As Global.Profiles.Web.Paginator

    '''<summary>
    '''pnlNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNote As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''labelAddEditNoteTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelAddEditNoteTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''valNoteSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNoteSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valNote As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valCusNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valCusNote As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnSaveNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNote As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNote As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dsNoteList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsNoteList As Global.Csla.Web.CslaDataSource
End Class
