'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Paginator

	'''<summary>
	'''PagerFirst control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PagerFirst As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''PagerLast control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PagerLast As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''PagerNextNext control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PagerNextNext As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''PagerPrevPrev control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PagerPrevPrev As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''PagerPrev control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PagerPrev As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''PagerNext control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PagerNext As Global.System.Web.UI.WebControls.LinkButton
End Class
