'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProfileSectionLinks

    '''<summary>
    '''litPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPrint As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litSummaryProfileReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSummaryProfileReport As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litSummaryPrioritisationReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSummaryPrioritisationReport As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litProfileReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProfileReports As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litReferences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReferences As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rptSectionLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSectionLinks As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''dsProfileSectionInfoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsProfileSectionInfoList As Global.Csla.Web.CslaDataSource

    '''<summary>
    '''scpProxy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scpProxy As Global.System.Web.UI.ScriptManagerProxy
End Class
