'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReferenceTableAuditTrail

    '''<summary>
    '''lnkReferenceTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReferenceTable As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUpdate As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''PaginatorPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaginatorPageSize As Global.Profiles.Web.PaginatorPageSize

    '''<summary>
    '''grdAuditTrail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAuditTrail As Global.Profiles.WebControls.Profiles.WebControls.GridViewExternalPaging

    '''<summary>
    '''dsReferenceDataAuditTrailInfoList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsReferenceDataAuditTrailInfoList As Global.Csla.Web.CslaDataSource

    '''<summary>
    '''bottomPaginator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottomPaginator As Global.Profiles.Web.Paginator

    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlAuditDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAuditDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPanelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPanelTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOldValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOldValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOldValueSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOldValueSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNewValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNewValueSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewValueSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUserSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDateOfChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateOfChange As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateOfChangeSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateOfChangeSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtReasonForChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReasonForChange As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReasonForChangeSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReasonForChangeSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
