'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Search

    '''<summary>
    '''udpSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents udpSearch As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ctlLetterSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlLetterSelector As Global.Profiles.WebControls.Profiles.WebControls.SearchControls.AlphabetSelector

    '''<summary>
    '''chkDisplayPublished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisplayPublished As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDisplayDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisplayDraft As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDisplayScenarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisplayScenarios As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDisplayMyProfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisplayMyProfiles As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''speciesFilterButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents speciesFilterButton As Global.Profiles.Web.Accordion

    '''<summary>
    '''spsSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spsSelector As Global.Profiles.Web.SpeciesSelector

    '''<summary>
    '''lblAffectedSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAffectedSpecies As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbExactWordOrPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbExactWordOrPhase As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbExactAllWords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbExactAllWords As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ddlWordSearchType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWordSearchType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlSectionSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSectionSelection As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkUnselectSections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnselectSections As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rptSections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSections As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''spnResultsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnResultsCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSortBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PaginatorPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaginatorPageSize As Global.Profiles.Web.PageSizeList

    '''<summary>
    '''rptProfileList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProfileList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''noDataLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noDataLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bottomPaginator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottomPaginator As Global.Profiles.Web.Paginator

    '''<summary>
    '''pnlProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProgress As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProgressHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProgressHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProgress As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''mpeProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeProgress As Global.AjaxControlToolkit.ModalPopupExtender
End Class
