'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SectionPagination

    '''<summary>
    '''lnkPreviousSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPreviousSection As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblPreviousSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreviousSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkNextSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNextSection As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblNextSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNextSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
