'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SpeciesSelector

    '''<summary>
    '''lblAffectedSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAffectedSpecies As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''speciesTreeToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents speciesTreeToggle As Global.Profiles.Web.TreeViewToggleButton

    '''<summary>
    '''tvwSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvwSpecies As Global.Telerik.Web.UI.RadTreeView
End Class
